# Agent
algorithm : "DQN"
EPISODES : 2500

# Environment
environment : "TrafficEnv"
RENDER_MODE : "sumo"

# Run
DEVICE : cuda
SEED : 0
mode : "train"

#Hyperparameters
ALPHA : 0.0002
GAMMA : 0.99
EPSILON : 1.0
EPSILON_DECAY : 0.9991
EPSILON_THRESHOLD: 0.05

#Save
PATH : "../algorithms/neural_networks/models"
#Load
PATH_TEST : "/home/sztaki/Documents/ICINCO_2024_rl_crossing-/algorithms/neural_networks/models/TrafficEnv_DQN_1740508672.5055716_4.pth"
